# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = '../platforms'


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1085, 428)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(470, 20, 171, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 110, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 230, 61, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(550, 230, 47, 13))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(540, 100, 71, 21))
        self.label_5.setObjectName("label_5")
        self.btn_gen_keys = QtWidgets.QPushButton(self.centralwidget)
        self.btn_gen_keys.setGeometry(QtCore.QRect(680, 50, 91, 23))
        self.btn_gen_keys.setObjectName("btn_gen_keys")
        self.btn_Encrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Encrypt.setGeometry(QtCore.QRect(190, 340, 71, 23))
        self.btn_Encrypt.setObjectName("btn_Encrypt")
        self.btn_Decrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Decrypt.setGeometry(QtCore.QRect(390, 340, 71, 23))
        self.btn_Decrypt.setObjectName("btn_Decrypt")
        self.btn_Sign = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Sign.setGeometry(QtCore.QRect(670, 340, 91, 23))
        self.btn_Sign.setObjectName("btn_Sign")
        self.btn_Verify = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Verify.setGeometry(QtCore.QRect(850, 340, 91, 23))
        self.btn_Verify.setObjectName("btn_Verify")
        self.txt_plain_text = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_plain_text.setGeometry(QtCore.QRect(140, 100, 381, 101))
        self.txt_plain_text.setObjectName("txt_plain_text")
        self.txt_Information = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_Information.setGeometry(QtCore.QRect(620, 100, 381, 101))
        self.txt_Information.setObjectName("txt_Information")
        self.txt_Cipher_text = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_Cipher_text.setGeometry(QtCore.QRect(140, 220, 381, 101))
        self.txt_Cipher_text.setObjectName("txt_Cipher_text")
        self.txt_Signature = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_Signature.setGeometry(QtCore.QRect(620, 220, 381, 101))
        self.txt_Signature.setObjectName("txt_Signature")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1085, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "RSA CIPHER"))
        self.label_2.setText(_translate("MainWindow", "Plain Text"))
        self.label_3.setText(_translate("MainWindow", "Cipher Text"))
        self.label_4.setText(_translate("MainWindow", "Signature"))
        self.label_5.setText(_translate("MainWindow", "Information"))
        self.btn_gen_keys.setText(_translate("MainWindow", "Generate Keys"))
        self.btn_Encrypt.setText(_translate("MainWindow", "Encrypt"))
        self.btn_Decrypt.setText(_translate("MainWindow", "Decrypt"))
        self.btn_Sign.setText(_translate("MainWindow", "Sign"))
        self.btn_Verify.setText(_translate("MainWindow", "Verify"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
